package com.kaosnet.krank

import java.io.DataOutputStream
import java.io.File
import java.io.FileOutputStream

/**
 * Writes Guitar Pro 5 (.gp5) binary files from TabNoteData.
 * Based on the reverse-engineered GP5 format specification.
 */
object Gp5Exporter {

    private const val TICKS_PER_QUARTER = 120
    private const val STRING_COUNT = 6
    private val STANDARD_TUNING = intArrayOf(40, 45, 50, 55, 59, 64) // E A D G B E (MIDI notes)

    fun export(
        notes: List<TabNoteData>,
        path: String,
        tempo: Float = 120f,
        title: String = "KRANK Transcription",
        tuning: IntArray = STANDARD_TUNING
    ): Boolean {
        return try {
            val file = File(path)
            DataOutputStream(FileOutputStream(file)).use { out ->
                writeHeader(out)
                writeScoreInfo(out, title)
                writeSystems(out, notes, tempo)
                writeTracks(out, tuning)
                writeMeasures(out, notes, tempo)
            }
            true
        } catch (e: Exception) {
            e.printStackTrace()
            false
        }
    }

    // ── HEADER ──

    private fun writeHeader(out: DataOutputStream) {
        // Magic + version string
        val magic = "FICHIER GUITAR PRO v5.00"
        out.write(magic.toByteArray(Charsets.US_ASCII))
        // Pad to 30 bytes with nulls (0x00), then \r\n
        repeat(30 - magic.length) { out.writeByte(0) }
        out.writeByte('\r'.code)
        out.writeByte('\n'.code)
        // Version byte
        out.writeByte(0)
    }

    // ── SCORE INFORMATION ──

    private fun writeScoreInfo(out: DataOutputStream, title: String) {
        // Title
        writeGpString(out, title)
        // Subtitle
        writeGpString(out, "")
        // Artist
        writeGpString(out, "")
        // Album
        writeGpString(out, "KRANK STUDIO")
        // Composer
        writeGpString(out, "")
        // Copyright
        writeGpString(out, "Generated by KRANK STUDIO")
        // Transcriber
        writeGpString(out, "")
        // Instructions
        writeGpString(out, "")
        // Notice (3 lines)
        writeGpString(out, "")
        writeGpString(out, "")
        writeGpString(out, "")
        // Triplet feeling
        out.writeByte(1) // 1 = eighth note triplet, 2 = sixteenth note triplet
    }

    // ── SYSTEMS/LYRICS ──

    private fun writeSystems(out: DataOutputStream, notes: List<TabNoteData>, tempo: Float) {
        // Lyrics - no lyrics
        out.writeByte(0) // no lyrics
        out.writeByte(0) // lyrics language

        // Tempo
        out.writeInt((tempo.coerceIn(30f, 300f)).toInt())

        // Key signature (0 = C)
        out.writeByte(0)

        // Octave
        out.writeByte(0)

        // Time signature
        out.writeByte(4) // numerator
        out.writeByte(2) // denominator exponent (2 => 2^2 = 4, i.e., quarter note)

        // Measure count
        val measures = computeMeasures(notes)
        val numMeasures = if (measures.isEmpty()) 1 else measures.size
        out.writeByte(numMeasures.coerceIn(1, 255))

        // Track count
        out.writeByte(1) // single track
    }

    // ── TRACKS ──

    private fun writeTracks(out: DataOutputStream, tuning: IntArray) {
        // Track name (length-prefixed with 4-byte int)
        writeGpStringInt(out, "Guitar")

        // Number of strings
        out.writeInt(STRING_COUNT)

        // Tuning (7 ints, pad with 0)
        for (i in 0 until 7) {
            if (i < tuning.size) out.writeInt(tuning[i])
            else out.writeInt(0)
        }

        // Port
        out.writeInt(1) // MIDI port 1

        // Channel
        out.writeInt(0) // MIDI channel 0

        // Channel effects
        out.writeInt(1) // channel effects

        // Fret count
        out.writeInt(24)

        // Capo
        out.writeInt(0)

        // Color (RGB)
        out.writeByte(0x22) // R
        out.writeByte(0xD3) // G
        out.writeByte(0xEE) // B

        // Show tuning (1 byte boolean)
        out.writeByte(1)

        // Flags: autoAccent, autoBrush, autoTapping,... etc
        // 0x00 = none
        out.writeByte(0)

        // Instrument (1 byte)
        out.writeByte(25) // 25 = Overdriven Guitar

        // Short name (string)
        writeGpString(out, "Gtr")

        // longName (string, 35 chars padded)
        val longName = "Guitar".padEnd(35)
        out.write(longName.toByteArray(Charsets.US_ASCII), 0, 35)

        // MIDI bank + volume + pan + chorus + reverb + phaser + tremolo
        out.writeByte(0)  // bank
        out.writeByte(104) // volume
        out.writeByte(64) // pan
        out.writeByte(0)  // chorus
        out.writeByte(64) // reverb
        out.writeByte(0)  // phaser
        out.writeByte(0)  // tremolo

        // Number of 8-velocities (1 byte)
        out.writeByte(0)
    }

    // ── MEASURES ──

    private data class MeasureData(
        val index: Int,
        val beats: List<BeatData>
    )

    private data class BeatData(
        val tickPos: Int,       // in ticks from measure start
        val duration: Int,      // in ticks
        val notes: List<NoteData>
    )

    private data class NoteData(
        val string: Int,   // 0-5 (high E to low E)
        val fret: Int,
        val duration: Int
    )

    private fun computeMeasures(notes: List<TabNoteData>): List<MeasureData> {
        if (notes.isEmpty()) {
            // One empty measure with 4/4 rest
            return listOf(MeasureData(0, emptyList()))
        }

        val ticksPerQtr = TICKS_PER_QUARTER
        val ticksPerMeasure = ticksPerQtr * 4 // 480 ticks for 4/4

        // Convert seconds to ticks for a tempo of 120 BPM
        // ticks = time_seconds * (tempo * ticksPerQuarter / 60)
        // We'll use the first note's time to estimate tempo or use default
        val maxTime = notes.maxOf { it.startTime + it.duration }

        // Compute tick positions for each note
        // For 120 BPM: 120 * 120 / 60 = 240 ticks per second
        val ticksPerSecond = 240.0 // 120 BPM * 120 TPQ / 60
        val notesWithTicks = notes.map { note ->
            val tickStart = (note.startTime * ticksPerSecond).toInt()
            val tickDur = ((note.duration * ticksPerSecond).toInt()).coerceAtLeast(ticksPerQtr / 4)
            NoteWithTick(note.stringNum, note.fret, tickStart, tickDur)
        }

        // Group into measures
        val maxTicks = (maxTime * ticksPerSecond).toInt() + 1
        val numMeasures = ((maxTicks / ticksPerMeasure) + 1).coerceAtLeast(1)
        val validMeasures = numMeasures.coerceIn(1, 255)

        val measures = mutableListOf<MeasureData>()
        for (m in 0 until validMeasures) {
            val measureStartTick = m * ticksPerMeasure
            val measureEndTick = measureStartTick + ticksPerMeasure

            // Get notes in this measure
            val measureNotes = notesWithTicks.filter {
                it.tickStart >= measureStartTick && it.tickStart < measureEndTick
            }

            if (measureNotes.isEmpty()) {
                // Empty measure
                measures.add(MeasureData(m, emptyList()))
                continue
            }

            // Group notes into beats (notes starting at same tick)
            val beatMap = mutableMapOf<Int, MutableList<NoteData>>()
            for (nt in measureNotes) {
                val beatTick = nt.tickStart - measureStartTick
                beatMap.getOrPut(beatTick) { mutableListOf() }
                    .add(NoteData(nt.stringNum, nt.fret, nt.tickDur.coerceAtLeast(ticksPerQtr / 4)))
            }

            // Sort beat positions and compute durations
            val sortedBeatTicks = beatMap.keys.sorted()
            val beats = mutableListOf<BeatData>()
            for (i in sortedBeatTicks.indices) {
                val tick = sortedBeatTicks[i]
                val nextTick = if (i + 1 < sortedBeatTicks.size)
                    sortedBeatTicks[i + 1] else ticksPerMeasure
                val duration = (nextTick - tick).coerceAtLeast(ticksPerQtr / 4)
                beats.add(BeatData(tick, duration, beatMap[tick]!!))
            }

            measures.add(MeasureData(m, beats))
        }

        return measures
    }

    private data class NoteWithTick(val stringNum: Int, val fret: Int, val tickStart: Int, val tickDur: Int)

    private fun writeMeasures(out: DataOutputStream, notes: List<TabNoteData>, tempo: Float) {
        val measures = computeMeasures(notes)
        if (measures.isEmpty()) {
            // Write one empty measure
            writeSingleMeasure(out, null)
            return
        }

        for (measure in measures) {
            writeSingleMeasure(out, measure)
        }
    }

    private fun writeSingleMeasure(out: DataOutputStream, measure: MeasureData?) {
        if (measure == null || measure.beats.isEmpty()) {
            // Empty measure with rest
            // Measure header flags (1 byte): 0x80 = empty/rest
            out.writeByte(0x80) // empty measure
            return
        }

        // Measure header flags
        // bit 0: time signature change
        // bit 1: key signature change
        // bit 2: beginning of repeat
        // bit 3: end of repeat
        // bit 5: marker
        // bit 6: has a chord
        // bit 7: non-empty measure indicator
        var headerFlags = 0

        // Only flag if beats exist (first beat has notes)
        val hasNotes = measure.beats.any { it.notes.isNotEmpty() }
        if (hasNotes) {
            headerFlags = headerFlags or 0x80 // non-empty
        }

        // Time signature for first measure
        if (measure.index == 0) {
            headerFlags = headerFlags or 0x01 // time sig change
            headerFlags = headerFlags or 0x40 // chord flag
        }

        out.writeByte(headerFlags)

        // If time signature change
        if (headerFlags and 0x01 != 0) {
            out.writeByte(4) // numerator
            out.writeByte(2) // denominator exponent
            out.writeByte(0) // number of beats per measure in display (0 = default)
        }

        // If key signature change
        if (headerFlags and 0x02 != 0) {
            out.writeByte(0) // key (C)
            out.writeByte(1) // mode (0 = minor, 1 = major) - actually seventh?
        }

        // If beginning of repeat
        if (headerFlags and 0x04 != 0) {
            out.writeByte(0) // repeat count
        }

        // If end of repeat
        if (headerFlags and 0x08 != 0) {
            out.writeByte(0) // repeat count
        }

        // Flag for number of beats
        var numBeatsFlag = 0
        if (measure.beats.size > 0) numBeatsFlag = numBeatsFlag or 0x20
        if (measure.beats.size > 1) numBeatsFlag = numBeatsFlag or 0x40
        if (measure.beats.size > 3) numBeatsFlag = numBeatsFlag or 0x80
        out.writeByte(numBeatsFlag)

        // Number of beats (variable length)
        if (numBeatsFlag == 0) return // no beats

        // Write beats using variable-length encoding
        var beatsRemaining = measure.beats.size
        while (beatsRemaining >= 0x20) {
            out.writeByte((beatsRemaining and 0x7F) or 0x80)
            beatsRemaining = beatsRemaining shr 7
        }
        out.writeByte(beatsRemaining and 0x7F)

        // Write each beat
        for (beat in measure.beats) {
            writeBeat(out, beat)
        }
    }

    private fun writeBeat(out: DataOutputStream, beat: BeatData) {
        if (beat.notes.isEmpty()) {
            // Rest beat
            var beatFlags = 0x20 // rest
            // Duration
            val durType = tickDurationToGpDuration(beat.duration)
            out.writeByte(beatFlags)
            out.writeByte(durType)
            return
        }

        // Beat flags
        // bit 0-1: 0=normal, 1=accentuated, 2=heavily accentuated, 3=let ring... etc
        // bit 2: rest 
        // bit 3: dotted note
        // bit 5: has notes
        // bit 6: has chord diagram
        // bit 7: has effects
        var beatFlags = 0x04 // has notes

        // Check if dotted
        if (isDotted(beat.duration)) {
            beatFlags = beatFlags or 0x08
        }

        // Check if all rest
        val hasNotes = beat.notes.any { it.fret >= 0 }
        if (!hasNotes) {
            beatFlags = beatFlags or 0x20 // rest
        }

        out.writeByte(beatFlags)

        // Duration type (byte)
        val durType = tickDurationToGpDuration(beat.duration)
        out.writeByte(durType)

        // Dotted (if dotted)
        if (beatFlags and 0x08 != 0) {
            out.writeByte(1) // dotted
        }

        // Effects (if any)
        if (beatFlags and 0x80 != 0) {
            // Write effects header
            out.writeByte(0) // no effects
        }

        // Number of notes
        val validNotes = beat.notes.filter { it.fret >= 0 }
        out.writeByte(validNotes.size)

        // Write each note
        for (note in validNotes) {
            writeNote(out, note)
        }
    }

    private fun writeNote(out: DataOutputStream, note: NoteData) {
        // Note flags
        // bit 0: tie note
        // bit 1: dead note
        // bit 2: ghost note
        // bit 4: has effects
        var noteFlags = 0

        if (note.fret == -1) {
            noteFlags = noteFlags or 0x02 // dead note
        }

        out.writeByte(noteFlags)

        // String number (0-5, where 0 = high E)
        out.writeByte(note.stringNum)

        // Fret number
        out.writeByte(note.fret.coerceIn(0, 24))

        // Effects byte
        if (noteFlags and 0x10 != 0) {
            // Effects header
            out.writeByte(0) // no effects
        }

        // Dynamic (0-15)
        out.writeByte(15) // fortissimo = loudest

        // Fret type (0 = normal, 1 = artificial harmonic, 2 = natural harmonic, ...)
        out.writeByte(0) // normal

        // Duration in ticks (2 bytes, big-endian)
        val durTicks = note.duration.coerceIn(1, 960)
        out.writeByte((durTicks shr 8) and 0xFF)
        out.writeByte(durTicks and 0xFF)
    }

    // ── HELPERS ──

    private fun writeGpString(out: DataOutputStream, str: String) {
        val bytes = str.toByteArray(Charsets.UTF_8)
        val len = bytes.size.coerceIn(0, 255)
        out.writeByte(len)
        if (len > 0) out.write(bytes, 0, len)
    }

    private fun writeGpStringInt(out: DataOutputStream, str: String) {
        val bytes = str.toByteArray(Charsets.UTF_8)
        out.writeInt(bytes.size)
        if (bytes.size > 0) out.write(bytes, 0, bytes.size)
    }

    /**
     * Maps a tick duration to GP5 duration type.
     * Duration types: 1=whole, 2=half, 4=quarter, 8=eighth, 16=16th, 32=32nd, 64=64th
     */
    private fun tickDurationToGpDuration(ticks: Int): Int {
        // At TICKS_PER_QUARTER = 120, a quarter note = 120 ticks
        val qtr = TICKS_PER_QUARTER
        return when {
            ticks >= qtr * 3 -> 2  // half note or longer
            ticks >= qtr * 1.5 -> 2
            ticks >= qtr * 0.75 -> 4  // quarter note
            ticks >= qtr * 0.375 -> 8 // eighth note
            ticks >= qtr * 0.1875 -> 16 // 16th note
            else -> 32 // 32nd note
        }
    }

    private fun isDotted(ticks: Int): Boolean {
        val qtr = TICKS_PER_QUARTER
        // Check if duration is close to a dotted value
        val dotted8 = qtr * 3 / 4  // dotted eighth = 3/4 quarter
        val dotted16 = qtr * 3 / 8 // dotted sixteenth
        val diff = Math.abs(ticks - dotted8)
        val diff2 = Math.abs(ticks - dotted16)
        return (diff < qtr / 8) || (diff2 < qtr / 8)
    }
}
